language: node_js
node_js:
- 11
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: ryan.goessl@d2l.com
  api_key:
    secure: Q7oxFccoVLvENsX59tZ3QEFJcD5a/HPWKlafR22vuPPXD+nn8gsX6HxNJ1sWafDxBqTB07gdIFo4fYiPNTpJWiz/B6IEgwdlMHf90BCoNh5jN9gQiyEFLjBgJThF61FHfL23pfAeJom5DkaYwWuJpHx4iYG/2f7iXKFrSD8ioItOMCVQCq+LuPsiQs1YItEkOp3JPh5m3hR/oIJ1VUNwRkgwwj+Jj3YYVbLOR/e8qpgKsbXGoLb0mFKi2qFxXHz/ZgGkGU0lWEqwSlvKDw4bn4YXJLa7GgoA8pgz9SDDK8ErD2gLe3xOAT1N4lirOdA6idywepHqvLDhArOG0C6OsAzSMh6F8yDfLvOeUeYPTqeSfjCVjSqcORPhSOgDWS8EcKdIpMa2MEcOJ/v0Hllyu7Onmy8AltjwdxBl/MVWodw8aVoesp4kliP6/NbvZPDCn+fMdmgpNIu/i1nso9sdiUDmF9o4QYJsAWeBbIP9dHkbBB182mrKHn1CNcVNDXDattfOlTcLdxkgC2JQFAyAgTqfQ7JPrhTClDdzog3kepLkRXVEFkR5vpl36FxiJfsc7Hv4kXWqQTHH22sEhF8mnZmXQUw6qqN1kwJCY1MT3JKrP3WMxqvt+LlAFPuiAmfGSk6OZ8tQdl+XOVje3FIJqV1y8KCF+VP1PYK8310r124=
  on:
    tags: true
    branch: master
env:
  global:
  - REPO_NAME=d2l-polymer-langtools
